---
- hosts: ec2
  become: yes
  vars:
    project_dir: /home/ec2-user/spe-project
    ansible_python_interpreter: /usr/bin/python3  # Ensure Ansible uses the correct Python interpreter

  tasks:
    - name: Gathering Facts
      setup:

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose using pip
      pip:
        name: docker-compose
        state: present

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "adityavit36/carprice:latest"
        - "adityavit36/predictor-app:latest"
        - "adityavit36/model-loader:latest"

    - name: Create Docker Compose file
      copy:
        content: |
          services:
            model-loader:
              image: adityavit36/model-loader
            predictor:
              image: adityavit36/predictor-app
              ports:
                - "5000:5000"
              depends_on:
                - model-loader
              environment:
                - MODEL_PATH=/app
            carprice:
              image: adityavit36/carprice
              ports:
                - "3000:3000"
              environment:
                - PREDICTOR_URL=http://localhost:5000/predict
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
      register: docker_compose_output
      ignore_errors: yes
