version: '3.7'

services:

  model-loader:
    image: adityavit36/model1
    depends_on:
      - logstash
    networks:
      - elastic-net

  predictor:
    image: adityavit36/pred1
    ports:
      - "5000:5000"
    depends_on:
      - model-loader
      - logstash
    environment:
      - MODEL_PATH=/app
    networks:
      - elastic-net

  carprice:
    image: adityavit36/car1
    ports:
      - "3000:3000"
    environment:
      - PREDICTOR_URL=http://localhost:5000/predict
    depends_on:
      - logstash
    networks:
      - elastic-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    ports:
      - "5044:5044"
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    volumes:
      - /home/aditya/adityamin/MLOPS/mlops/src/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic-net

volumes:
  esdata:

networks:
  elastic-net:
    driver: bridge
