version: '3.7'
services:
  model-loader:
    image: adityavit36/model1
    depends_on:
      - logstash
    networks:
      - app-network

  predictor:
    image: adityavit36/pred1
    ports:
      - "5000:5000"
    depends_on:
      - model-loader
      - logstash
    environment:
      - MODEL_PATH=/app
    networks:
      - app-network

  carprice:
    image: adityavit36/car1
    ports:
      - "3000:3000"
    environment:
      - PREDICTOR_URL=http://predictor:5000/predict
    depends_on:
      - logstash
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"  # Exposing internal port 9200 to external port 9201
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]  # Keep as localhost:9200 since it's internal
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9201  # Ensure it points to the correct port
    networks:
      - app-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    ports:
      - "5044:5044"
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - xpack.monitoring.elasticsearch.hosts=["http://elasticsearch:9201"]
    networks:
      - app-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    depends_on:
      - logstash
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

volumes:
  esdata:

networks:
  app-network:
    driver: bridge
