version: '3.7'

services:
  model-loader:
    image: adityavit36/model1
    # No need for volumes in this case
    # Other configurations for model-loader

  predictor:
    image: adityavit36/pred1
    ports:
      - "5000:5000"
    depends_on:
      - model-loader
    environment:
      - MODEL_PATH=/app  # Assuming model_file.pkl is in the same directory as predictor.py and model_loader.py
    # Other configurations for predictor-app

  carprice:
    image: adityavit36/car1
    ports:
      - "3000:3000"
    environment:
       - PREDICTOR_URL=http://localhost:5000/predict
    # Other configurations for carprice
